global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
    
  - job_name: "B09-COLIN02"
    static_configs:
    - targets: ["192.168.66.138:9100"]

remote_write:
  - url: "http://localhost:42699/prometheus/v1/receive"
    basic_auth:
      username: "admin"
      password: "admin"
